export const CREDENTIAL_REQUEST_REPOSITORY_PORT = Symbol("CREDENTIAL_REQUEST_REPOSITORY_PORT");
export const LOCK_REPOSITORY_PORT = Symbol("LOCK_REPOSITORY_PORT");
export const AUDIT_EVENT_REPOSITORY_PORT = Symbol("AUDIT_EVENT_REPOSITORY_PORT");